/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Trashify } from "./Trashify";
export * as factories from "./factories";
export { Trashify__factory } from "./factories/Trashify__factory";
