// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Trashify$Type } from "./Trashify";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Trashify"]: Trashify$Type;
    ["contracts/Trashify.sol:Trashify"]: Trashify$Type;
  }
}
